<?php
$translate = $this->plugin('translate');
$hyperlink = $this->plugin('hyperlink');
$url = $this->plugin('url');
$this->htmlElement('body')->appendAttribute('class', 'index search');
?>

<?php echo $this->pageTitle(sprintf($translate('Search results for “%s”'), $query)); ?>

<?php if (empty($results)) : ?>
    <p><?php echo $translate('No result found'); ?></p>
<?php else : ?>
    <?php
    $resourceLabels = [
        'site_pages' => 'Site pages', // @translate
        'items' => 'Items', // @translate
        'item_sets' => 'Item sets', // @translate
        'media' => 'Media', // @translate
    ];
    $resourceControllers = [
        'site_pages' => 'page',
        'items' => 'item',
        'item_sets' => 'item-set',
        'media' => 'media',
    ];
    ?>
    <?php foreach ($results as $resourceName => $result) : ?>
        <div class="<?php echo $resourceName; ?> results" data-equalizer data-equalize-on="medium">
            <h2><?php echo $translate($resourceLabels[$resourceName]); ?></h2>

            <?php $titleMethod = $resourceName === 'site_pages' ? 'title' : 'displayTitle'; ?>
            <ul>
                <?php foreach ($result['resources'] as $resource) : ?>

                    <li>
                        <?php if ($resourceName == 'items') : ?>
                            <?php
                            $dcdateExist =  method_exists($resource, 'value');
                            $dcDate = $dcdateExist ? $resource->value('dcterms:date') : '';
                            ?>
                            <div class=" itemCallouts searchItem" data-equalizer-watch>
                                <p><?php echo $resource->linkRaw($this->thumbnail($resource, 'medium', ['title' => $resource->$titleMethod(), 'alt' => $resource->$titleMethod()])); ?></p>
                                <p><?php if ($dcdateExist && $dcDate != '') echo '<p>Date: ' . $dcDate . '</p>';
                                    else echo $dcDate; ?></p>
                                <p><?php echo $resource->link($resource->$titleMethod()); ?></p>
                            </div>
                        <?php else : ?>
                            <p><?php echo $resource->link($resource->$titleMethod()); ?></p>
                        <?php endif; ?>

                    </li>
                <?php endforeach; ?>
            </ul>
            <?php echo $hyperlink(
                sprintf($translate('View all results (%s total)'), $result['total']),
                $url(
                    'site/resource',
                    ['controller' => $resourceControllers[$resourceName], 'action' => 'browse'],
                    ['query' => ['fulltext_search' => $query]],
                    true
                )
            ); ?>
        </div>
    <?php endforeach; ?>
<?php endif; ?>